name: Weekly Competitor Scraper

on:
  schedule:
    - cron: '0 23 * * 0'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    permissions:
      issues: write # Gives GitHub permission to open an issue and email you
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install requests beautifulsoup4

    - name: Run Script
      run: python scraper.py

    - name: Trigger Automated Email
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        REPORT_BODY=$(cat weekly_report.txt)
        gh issue create \
          --title "SRP | Weekly cometitor insights" \
          --body "$REPORT_BODY"
